### PR TITLE
Remove breaking Reporter changes

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
Also adds private Sender attributes and methods for ease of future
improvements.

Provides requested changes from recent https://github.com/jaegertracing/jaeger-client-python/pull/186 review

Signed-off-by: Ryan Fitzpatrick <rmfitzpatrick@signalfx.com>

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
@ProvoK, any suggestions to better meet requested changes would be appreciated.

**Comment by ProvoK** [comment]
@rmfitzpatrick 
I'm sorry but I'm actually on vacation, I cannot check nor requested changes nor your PR, I'll be back the next week.

**Comment by rmfitzpatrick** [comment]
@ProvoK, sorry to rush you after your vacation but I wonder if you'd had any chance to look at this and its parent review?  Let me know if you'd prefer I open an updated version of https://github.com/jaegertracing/jaeger-client-python/pull/186 since I may have more cycles for it than you.

**Comment by ProvoK** [comment]
@rmfitzpatrick Sorry for the delay. It's pretty obvious I'm too busy atm and I've not time to follow all discussions and changes. So yeah it's probably better if you make another PR and https://github.com/jaegertracing/jaeger-client-python/pull/186 get closed. 

Edit: Thanks a lot anyway for you patience and your PRs, hope you'll get this done!

**Comment by rmfitzpatrick** [comment]
Not a problem and thank you for getting this all started!

**Pull request closed without merging**
